export const categories = [
    {name: "Tshirt", sku: "TST"},
    {name: "Shirt", sku: "SHT"},
    {name: "Pants", sku: "PNT"},
    {name: "Shoes", sku: "SHS"},
    {name: "Hoodie", sku: "HDI"},
    {name: "Jacket", sku: "JKT"},
    {name: "Shorts", sku: "SRT"},
    {name: "Sweater", sku: "SWT"},
    {name: "Socks", sku: "SKS"},
    {name: "Underwear", sku: "UWD"},
    {name: "Accessories", sku: "ACC"},
    {name: "Other", sku: "OTH"},
] as const

export const categoryNames = [
    "👕 Tshirt",
    "👔 Shirt",
    "👖 Pants",
    "👟 Shoes",
    "🧥 Hoodie",
    "🧥 Jacket",
    "🩳 Shorts",
    "🧶 Sweater",
    "🧦 Socks",
    "🩲 Underwear",
    "🎀 Accessories",
    "🔶 Other",
] as const

export const colors = [
    "🖤 Black",
    "⚪️ White",
    "❤️ Red",
    "💙 Blue",
    "💚 Green",
    "💛 Yellow",
    "🧡 Orange",
    "💜 Purple",
    "💗 Pink",
    "🟤 Brown",
    "🔘 Grey",
    "🟫 Beige",
    "🌈 Mixed",
] as const
